version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: celery
      POSTGRES_DB: celerydb
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  celery:
    build:
      context: .
    image: celery-app:latest
    restart: always
    volumes:
      - .:/app
    depends_on: 
      - db
    ports:
      - 5000:5000
      - 8000:8000
  web:
    image: nginx
    restart: always
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on: 
      - celery
volumes:
  dbdata:
  celeryconfig:
