version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: celery
      POSTGRES_DB: celerydb
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  celery:
    build:
      context: .
    image: celery-app:latest
    restart: always
    volumes:
      - .:/app
    depends_on: 
      - db
  web:
    build:
      context: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on: 
      - celery
volumes:
  dbdata:
  celeryconfig:
